// <auto-generated>
//
// This file was automatically generated by Interoptopus.
//
// Library:      gix_ffi
// Hash:         0xd164f5f2d6230bf7
// Namespace:    My.Company
// Builder:      interoptopus_csharp (0.16.4)
//
// Do not edit this file manually.
//
// </auto-generated>

// We use [Obsolete()] to discourage users calling internal code. Disable internal warnings about that.
#pragma warning disable CS0612 // Type or member is obsolete
#pragma warning disable CS0618 // Type or member is obsolete (with message)
// Simplifies codegen
#pragma warning disable CS0105 // The using directive appeared previously in this namespace
#nullable enable
// Generated interop code uses patterns that trigger nullable diagnostics
#pragma warning disable CS8600 // Converting null literal or possible null value to non-nullable type
#pragma warning disable CS8601 // Possible null reference assignment
#pragma warning disable CS8602 // Dereference of a possibly null reference
#pragma warning disable CS8603 // Possible null reference return
#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor
#pragma warning disable CS8625 // Cannot convert null literal to non-nullable reference type

#pragma warning disable 0105
using System;
using System.IO;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.ComponentModel;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Runtime.InteropServices.Marshalling;
using System.Runtime.CompilerServices;

#pragma warning restore 0105


namespace My.Company;

public static partial class Interop {

    public const string NativeLib = "gix_ffi";

    static Interop()
    {
        var api_version = Interop.__api_guard();
        if (api_version != 0xd164f5f2d6230bf7)
        {
            throw new TypeLoadException($"API reports hash 0x{api_version:X} which differs from hash in bindings (0xd164f5f2d6230bf7). You probably forgot to update / copy either the bindings or the library.");
        }
    }

    
    /// Absolute path of the `.git` directory.
    [LibraryImport(NativeLib, EntryPoint = "repo_git_dir")]
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    internal static partial ResultUtf8StringGixError repo_git_dir(IntPtr instance);


    
    /// Open an existing repository at `path`.
    [LibraryImport(NativeLib, EntryPoint = "repo_open")]
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    internal static partial ResultRepoGixError repo_open(Utf8String path);


    
    /// Whether this repository has no working tree.
    [LibraryImport(NativeLib, EntryPoint = "repo_is_bare")]
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    internal static partial Bool repo_is_bare(IntPtr instance);


    
    [LibraryImport(NativeLib, EntryPoint = "__api_guard")]
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    public static partial ulong __api_guard();


    
    [LibraryImport(NativeLib, EntryPoint = "interoptopus_string_clone")]
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    internal static partial long interoptopus_string_clone(IntPtr utf8, IntPtr rval);


    
    [LibraryImport(NativeLib, EntryPoint = "interoptopus_string_create")]
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    internal static partial long interoptopus_string_create(IntPtr utf8, ulong len, IntPtr rval);


    
    [LibraryImport(NativeLib, EntryPoint = "interoptopus_string_destroy")]
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    internal static partial long interoptopus_string_destroy(Utf8String utf8);


    
    [LibraryImport(NativeLib, EntryPoint = "repo_destroy")]
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    internal static partial void repo_destroy(IntPtr instance);


    
    [LibraryImport(NativeLib, EntryPoint = "interoptopus_string_clone")]
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    internal static partial long interoptopus_string_clone(ref Utf8String utf8, ref Utf8String rval);


    
    [LibraryImport(NativeLib, EntryPoint = "interoptopus_string_create")]
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    internal static partial long interoptopus_string_create(IntPtr utf8, ulong len, ref Utf8String rval);


    
    /// Absolute path of the `.git` directory.
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    internal static ResultUtf8StringGixError repo_git_dir(Repo instance)
    {
        return repo_git_dir(instance.Context);
    }

    
    /// Whether this repository has no working tree.
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    internal static Bool repo_is_bare(Repo instance)
    {
        return repo_is_bare(instance.Context);
    }

    
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    internal static void repo_destroy(Repo instance)
    {
        repo_destroy(instance.Context);
    }
}


/// Rust-like `Result` type usable over FFI.
/// <remarks>
/// ⚠️ This type is an owned resource. You must 1) either call `Dispose()` on it,
/// 2) call another method on it that promises to free it, or 3) 'move' it to Rust
/// if the type allows it.
/// </remarks>
public partial class ResultRepoGixError
{
    uint _variant;
    IntPtr _Ok;
    GixError _Err;
}


[NativeMarshalling(typeof(MarshallerMeta))]
public partial class ResultRepoGixError : IResult<IntPtr, GixError>, IDisposable
{
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe struct UnmanagedOk
    {
        internal uint _variant;
        internal IntPtr _Ok;
    }

    
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe struct UnmanagedErr
    {
        internal uint _variant;
        internal GixError.Unmanaged _Err;
    }

    

    [StructLayout(LayoutKind.Explicit)]
    internal unsafe struct Unmanaged
    {
        [FieldOffset(0)]
        internal uint _variant;

        [FieldOffset(0)]
        internal UnmanagedOk _Ok;

        [FieldOffset(0)]
        internal UnmanagedErr _Err;

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        [Obsolete("This method is intended for use by generated code only.")]
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal ResultRepoGixError IntoManaged()
        {
            var _managed = new ResultRepoGixError();
            _managed._variant = _variant;
            if (_variant == 0) _managed._Ok = _Ok._Ok;
            if (_variant == 1) _managed._Err = _Err._Err.IntoManaged();
            return _managed;
        }
    }


    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    [Obsolete("This method is intended for use by generated code only.")]
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal Unmanaged IntoUnmanaged()
    {
        var _unmanaged = new Unmanaged();
        _unmanaged._variant = _variant;
        if (_variant == 0) _unmanaged._Ok._Ok = _Ok;
        if (_variant == 1) _unmanaged._Err._Err = _Err.IntoUnmanaged();
        return _unmanaged;
    }


    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    [Obsolete("This method is intended for use by generated code only.")]
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal Unmanaged AsUnmanaged()
    {
        var _unmanaged = new Unmanaged();
        _unmanaged._variant = _variant;
        if (_variant == 0) _unmanaged._Ok._Ok = _Ok;
        if (_variant == 1) _unmanaged._Err._Err = _Err.AsUnmanaged();
        return _unmanaged;
    }


    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    public Exception ExceptionForVariant()
    {
        if (_variant == 0) return new EnumException<IntPtr>(_Ok);
        if (_variant == 1) return new EnumException<GixError>(_Err);
        if (_variant == 2) return new EnumException();
        if (_variant == 3) return new EnumException();
        throw new InteropException("Illegal enum state detected. This is a severe error and should never happen.");
    }


    // Ctors
    public static ResultRepoGixError Ok(IntPtr value) => new() { _variant = 0, _Ok = value };
    public static ResultRepoGixError Err(GixError value) => new() { _variant = 1, _Err = value };
    public static ResultRepoGixError Panic => new() { _variant = 2 };
    public static ResultRepoGixError Null => new() { _variant = 3 };

    // Checks
    public bool IsOk => _variant == 0;
    public bool IsErr => _variant == 1;
    public bool IsPanic => _variant == 2;
    public bool IsNull => _variant == 3;

    // Conversions
    public IntPtr AsOk() { if (_variant != 0) { throw ExceptionForVariant(); } else { return _Ok; } }
    public GixError AsErr() { if (_variant != 1) { throw ExceptionForVariant(); } else { return _Err; } }
    public void AsPanic() { if (_variant != 2) throw ExceptionForVariant(); }
    public void AsNull() { if (_variant != 3) throw ExceptionForVariant(); }


    // FromCall
    public static ResultRepoGixError FromCall(Func<IntPtr> func)
    {
        try { return Ok(func()); }
        catch (Exception) { return Panic; }
    }

    public static async Task<ResultRepoGixError> FromCallAsync(Func<Task<IntPtr>> func)
    {
        try { return Ok(await func()); }
        catch (OperationCanceledException) { throw; }
        catch (Exception) { return Panic; }
    }


    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    public override string ToString()
    {
        if (_variant == 0) return "Ok(...)";
        if (_variant == 1) return "Err(...)";
        if (_variant == 2) return "Panic";
        if (_variant == 3) return "Null";
        throw new InteropException("Illegal enum state detected. This is a severe error and should never happen.");
    }



    public void Dispose()
    {
        if (_variant == 1) _Err?.Dispose();
    }

    [CustomMarshaller(typeof(ResultRepoGixError), MarshalMode.Default, typeof(Marshaller))]
    private struct MarshallerMeta { }

    internal ref struct Marshaller
    {
        private ResultRepoGixError _managed;
        private Unmanaged _unmanaged;

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public Marshaller(ResultRepoGixError managed) { _managed = managed; }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public Marshaller(Unmanaged unmanaged) { _unmanaged = unmanaged; }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public void FromManaged(ResultRepoGixError managed) { _managed = managed; }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public void FromUnmanaged(Unmanaged unmanaged) { _unmanaged = unmanaged; }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public Unmanaged ToUnmanaged() { return _managed.IntoUnmanaged(); }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public ResultRepoGixError ToManaged() { return _unmanaged.IntoManaged(); }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public void Free() {}
    }

}



/// Rust-like `Result` type usable over FFI.
/// <remarks>
/// ⚠️ This type is an owned resource. You must 1) either call `Dispose()` on it,
/// 2) call another method on it that promises to free it, or 3) 'move' it to Rust
/// if the type allows it.
/// </remarks>
public partial class ResultUtf8StringGixError
{
    uint _variant;
    Utf8String _Ok;
    GixError _Err;
}


[NativeMarshalling(typeof(MarshallerMeta))]
public partial class ResultUtf8StringGixError : IResult<Utf8String, GixError>, IDisposable
{
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe struct UnmanagedOk
    {
        internal uint _variant;
        internal Utf8String.Unmanaged _Ok;
    }

    
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe struct UnmanagedErr
    {
        internal uint _variant;
        internal GixError.Unmanaged _Err;
    }

    

    [StructLayout(LayoutKind.Explicit)]
    internal unsafe struct Unmanaged
    {
        [FieldOffset(0)]
        internal uint _variant;

        [FieldOffset(0)]
        internal UnmanagedOk _Ok;

        [FieldOffset(0)]
        internal UnmanagedErr _Err;

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        [Obsolete("This method is intended for use by generated code only.")]
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal ResultUtf8StringGixError IntoManaged()
        {
            var _managed = new ResultUtf8StringGixError();
            _managed._variant = _variant;
            if (_variant == 0) _managed._Ok = _Ok._Ok.IntoManaged();
            if (_variant == 1) _managed._Err = _Err._Err.IntoManaged();
            return _managed;
        }
    }


    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    [Obsolete("This method is intended for use by generated code only.")]
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal Unmanaged IntoUnmanaged()
    {
        var _unmanaged = new Unmanaged();
        _unmanaged._variant = _variant;
        if (_variant == 0) _unmanaged._Ok._Ok = _Ok.IntoUnmanaged();
        if (_variant == 1) _unmanaged._Err._Err = _Err.IntoUnmanaged();
        return _unmanaged;
    }


    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    [Obsolete("This method is intended for use by generated code only.")]
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal Unmanaged AsUnmanaged()
    {
        var _unmanaged = new Unmanaged();
        _unmanaged._variant = _variant;
        if (_variant == 0) _unmanaged._Ok._Ok = _Ok.AsUnmanaged();
        if (_variant == 1) _unmanaged._Err._Err = _Err.AsUnmanaged();
        return _unmanaged;
    }


    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    public Exception ExceptionForVariant()
    {
        if (_variant == 0) return new EnumException<Utf8String>(_Ok);
        if (_variant == 1) return new EnumException<GixError>(_Err);
        if (_variant == 2) return new EnumException();
        if (_variant == 3) return new EnumException();
        throw new InteropException("Illegal enum state detected. This is a severe error and should never happen.");
    }


    // Ctors
    public static ResultUtf8StringGixError Ok(Utf8String value) => new() { _variant = 0, _Ok = value };
    public static ResultUtf8StringGixError Err(GixError value) => new() { _variant = 1, _Err = value };
    public static ResultUtf8StringGixError Panic => new() { _variant = 2 };
    public static ResultUtf8StringGixError Null => new() { _variant = 3 };

    // Checks
    public bool IsOk => _variant == 0;
    public bool IsErr => _variant == 1;
    public bool IsPanic => _variant == 2;
    public bool IsNull => _variant == 3;

    // Conversions
    public Utf8String AsOk() { if (_variant != 0) { throw ExceptionForVariant(); } else { return _Ok; } }
    public GixError AsErr() { if (_variant != 1) { throw ExceptionForVariant(); } else { return _Err; } }
    public void AsPanic() { if (_variant != 2) throw ExceptionForVariant(); }
    public void AsNull() { if (_variant != 3) throw ExceptionForVariant(); }


    // FromCall
    public static ResultUtf8StringGixError FromCall(Func<Utf8String> func)
    {
        try { return Ok(func()); }
        catch (Exception) { return Panic; }
    }

    public static async Task<ResultUtf8StringGixError> FromCallAsync(Func<Task<Utf8String>> func)
    {
        try { return Ok(await func()); }
        catch (OperationCanceledException) { throw; }
        catch (Exception) { return Panic; }
    }


    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    public override string ToString()
    {
        if (_variant == 0) return "Ok(...)";
        if (_variant == 1) return "Err(...)";
        if (_variant == 2) return "Panic";
        if (_variant == 3) return "Null";
        throw new InteropException("Illegal enum state detected. This is a severe error and should never happen.");
    }



    public void Dispose()
    {
        if (_variant == 0) _Ok?.Dispose();
        if (_variant == 1) _Err?.Dispose();
    }

    [CustomMarshaller(typeof(ResultUtf8StringGixError), MarshalMode.Default, typeof(Marshaller))]
    private struct MarshallerMeta { }

    internal ref struct Marshaller
    {
        private ResultUtf8StringGixError _managed;
        private Unmanaged _unmanaged;

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public Marshaller(ResultUtf8StringGixError managed) { _managed = managed; }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public Marshaller(Unmanaged unmanaged) { _unmanaged = unmanaged; }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public void FromManaged(ResultUtf8StringGixError managed) { _managed = managed; }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public void FromUnmanaged(Unmanaged unmanaged) { _unmanaged = unmanaged; }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public Unmanaged ToUnmanaged() { return _managed.IntoUnmanaged(); }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public ResultUtf8StringGixError ToManaged() { return _unmanaged.IntoManaged(); }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public void Free() {}
    }

}



/// The single error type crossing the boundary.
/// 
/// Deliberately coarse. `gix` error enums are mostly *struct* variants
/// (`LockCommit { source, full_name }`), and interoptopus payload enums
/// support single-field tuple variants only - struct variants and
/// multi-field tuple variants are explicitly unsupported. Rather than
/// introduce a companion `#[ffi]` struct per fielded variant across
/// hundreds of `gix` variants, the whole `Display`/`source` chain is
/// flattened into one message string here.
/// 
/// Each variant still becomes its own generated C# exception type, so
/// callers can catch by category. Finer per-domain error types can be
/// added later without breaking this one.
/// <remarks>
/// ⚠️ This type is an owned resource. You must 1) either call `Dispose()` on it,
/// 2) call another method on it that promises to free it, or 3) 'move' it to Rust
/// if the type allows it.
/// </remarks>
public partial class GixError
{
    byte _variant;
    Utf8String _NotARepository;
    Utf8String _Io;
    Utf8String _Config;
    Utf8String _Other;
}


[NativeMarshalling(typeof(MarshallerMeta))]
public partial class GixError : IDisposable
{
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe struct UnmanagedNotARepository
    {
        internal byte _variant;
        internal Utf8String.Unmanaged _NotARepository;
    }

    
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe struct UnmanagedIo
    {
        internal byte _variant;
        internal Utf8String.Unmanaged _Io;
    }

    
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe struct UnmanagedConfig
    {
        internal byte _variant;
        internal Utf8String.Unmanaged _Config;
    }

    
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe struct UnmanagedOther
    {
        internal byte _variant;
        internal Utf8String.Unmanaged _Other;
    }

    

    [StructLayout(LayoutKind.Explicit)]
    internal unsafe struct Unmanaged
    {
        [FieldOffset(0)]
        internal byte _variant;

        [FieldOffset(0)]
        internal UnmanagedNotARepository _NotARepository;

        [FieldOffset(0)]
        internal UnmanagedIo _Io;

        [FieldOffset(0)]
        internal UnmanagedConfig _Config;

        [FieldOffset(0)]
        internal UnmanagedOther _Other;

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        [Obsolete("This method is intended for use by generated code only.")]
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal GixError IntoManaged()
        {
            var _managed = new GixError();
            _managed._variant = _variant;
            if (_variant == 0) _managed._NotARepository = _NotARepository._NotARepository.IntoManaged();
            if (_variant == 1) _managed._Io = _Io._Io.IntoManaged();
            if (_variant == 2) _managed._Config = _Config._Config.IntoManaged();
            if (_variant == 3) _managed._Other = _Other._Other.IntoManaged();
            return _managed;
        }
    }


    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    [Obsolete("This method is intended for use by generated code only.")]
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal Unmanaged IntoUnmanaged()
    {
        var _unmanaged = new Unmanaged();
        _unmanaged._variant = _variant;
        if (_variant == 0) _unmanaged._NotARepository._NotARepository = _NotARepository.IntoUnmanaged();
        if (_variant == 1) _unmanaged._Io._Io = _Io.IntoUnmanaged();
        if (_variant == 2) _unmanaged._Config._Config = _Config.IntoUnmanaged();
        if (_variant == 3) _unmanaged._Other._Other = _Other.IntoUnmanaged();
        return _unmanaged;
    }


    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    [Obsolete("This method is intended for use by generated code only.")]
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal Unmanaged AsUnmanaged()
    {
        var _unmanaged = new Unmanaged();
        _unmanaged._variant = _variant;
        if (_variant == 0) _unmanaged._NotARepository._NotARepository = _NotARepository.AsUnmanaged();
        if (_variant == 1) _unmanaged._Io._Io = _Io.AsUnmanaged();
        if (_variant == 2) _unmanaged._Config._Config = _Config.AsUnmanaged();
        if (_variant == 3) _unmanaged._Other._Other = _Other.AsUnmanaged();
        return _unmanaged;
    }


    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    public Exception ExceptionForVariant()
    {
        if (_variant == 0) return new EnumException<Utf8String>(_NotARepository);
        if (_variant == 1) return new EnumException<Utf8String>(_Io);
        if (_variant == 2) return new EnumException<Utf8String>(_Config);
        if (_variant == 3) return new EnumException<Utf8String>(_Other);
        throw new InteropException("Illegal enum state detected. This is a severe error and should never happen.");
    }


    // Ctors
    /// Path exists but is not a repository, or could not be discovered.
    public static GixError NotARepository(Utf8String value) => new() { _variant = 0, _NotARepository = value };
    /// Filesystem or OS-level failure.
    public static GixError Io(Utf8String value) => new() { _variant = 1, _Io = value };
    /// Repository configuration could not be read or is invalid.
    public static GixError Config(Utf8String value) => new() { _variant = 2, _Config = value };
    /// Anything not yet categorised.
    public static GixError Other(Utf8String value) => new() { _variant = 3, _Other = value };

    // Checks
    public bool IsNotARepository => _variant == 0;
    public bool IsIo => _variant == 1;
    public bool IsConfig => _variant == 2;
    public bool IsOther => _variant == 3;

    // Conversions
    public Utf8String AsNotARepository() { if (_variant != 0) { throw ExceptionForVariant(); } else { return _NotARepository; } }
    public Utf8String AsIo() { if (_variant != 1) { throw ExceptionForVariant(); } else { return _Io; } }
    public Utf8String AsConfig() { if (_variant != 2) { throw ExceptionForVariant(); } else { return _Config; } }
    public Utf8String AsOther() { if (_variant != 3) { throw ExceptionForVariant(); } else { return _Other; } }


    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    public override string ToString()
    {
        if (_variant == 0) return "NotARepository(...)";
        if (_variant == 1) return "Io(...)";
        if (_variant == 2) return "Config(...)";
        if (_variant == 3) return "Other(...)";
        throw new InteropException("Illegal enum state detected. This is a severe error and should never happen.");
    }



    public void Dispose()
    {
        if (_variant == 0) _NotARepository?.Dispose();
        if (_variant == 1) _Io?.Dispose();
        if (_variant == 2) _Config?.Dispose();
        if (_variant == 3) _Other?.Dispose();
    }

    [CustomMarshaller(typeof(GixError), MarshalMode.Default, typeof(Marshaller))]
    private struct MarshallerMeta { }

    internal ref struct Marshaller
    {
        private GixError _managed;
        private Unmanaged _unmanaged;

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public Marshaller(GixError managed) { _managed = managed; }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public Marshaller(Unmanaged unmanaged) { _unmanaged = unmanaged; }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public void FromManaged(GixError managed) { _managed = managed; }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public void FromUnmanaged(Unmanaged unmanaged) { _unmanaged = unmanaged; }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public Unmanaged ToUnmanaged() { return _managed.IntoUnmanaged(); }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public GixError ToManaged() { return _unmanaged.IntoManaged(); }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public void Free() {}
    }

}


public partial class Repo : IDisposable
{
    private IntPtr _context;

    private Repo() {}

    
    
    /// Open an existing repository at `path`.
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    public static Repo Open(Utf8String path)
    {
        var self = new Repo();
        self._context = Interop.repo_open(path).AsOk();
        return self;
    }

    

    
    
    /// Absolute path of the `.git` directory.
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    public Utf8String GitDir()
    {
        return Interop.repo_git_dir(this).AsOk();
    }
    
    
    /// Whether this repository has no working tree.
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    public Bool IsBare()
    {
        return Interop.repo_is_bare(this);
    }
    

    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    public void Dispose()
    {
        Interop.repo_destroy(_context);
        _context = IntPtr.Zero;
    }

    internal IntPtr Context => _context;
}


[Serializable]
[StructLayout(LayoutKind.Sequential)]
public partial struct Bool
{
    byte value;
}

public partial struct Bool
{
    public static readonly Bool True = new Bool { value = 1 };
    public static readonly Bool False = new Bool { value = 0 };

    public Bool(bool b)
    {
        value = (byte)(b ? 1 : 0);
    }

    public bool Is => value == 1;

    public static implicit operator Bool(bool b) => new Bool(b);
    public static implicit operator bool(Bool b) => b.Is;
}

public partial class Utf8String
{
    IntPtr _ptr;
    ulong _len;
    ulong _capacity;
}

/// A Rust-allocated UTF-8 string.
///
/// This type wraps a native Rust <c>String</c> and provides zero-copy read access
/// via the <see cref="String"/> property.
/// <remarks>
/// ⚠️ This type is an owned resource. You must 1) either call `Dispose()` on it,
/// 2) call another method on it that promises to free it, or 3) 'move' it to Rust
/// if the type allows it.
/// </remarks>
[NativeMarshalling(typeof(MarshallerMeta))]
public partial class Utf8String : IDisposable
{
    private Utf8String() { }

    /// Creates a new Rust-owned <see cref="Utf8String"/> from a managed string.
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    public static unsafe Utf8String From(string s)
    {
        var rval = new Utf8String();
        var source = s.AsSpan();
        Span<byte> utf8Bytes = stackalloc byte[Encoding.UTF8.GetByteCount(source)];
        var len = Encoding.UTF8.GetBytes(source, utf8Bytes);

        fixed (byte* p = utf8Bytes)
        {
            InteropHelper.interoptopus_string_create((IntPtr)p, (ulong)len, out var native);
            rval._ptr = native._ptr;
            rval._len = native._len;
            rval._capacity = native._capacity;
        }

        return rval;
    }

    /// Creates an empty Rust-owned <see cref="Utf8String"/>.
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    public static unsafe Utf8String Empty()
    {
        InteropHelper.interoptopus_string_create(IntPtr.Zero, 0, out var _out);
        return _out.IntoManaged();
    }


    /// Converts the native UTF-8 buffer to a managed string, leaving the native buffer alive.
    /// The caller must still call <see cref="Dispose"/> to free the native memory.
    public unsafe string String
    {
        get
        {
            var span = new ReadOnlySpan<byte>((byte*)_ptr, (int)_len);
            var s = Encoding.UTF8.GetString(span);
            return s;
        }
    }

    /// Converts the native UTF-8 buffer to a managed string and disposes the native buffer.
    /// After this call the <see cref="Utf8String"/> instance is consumed and must not be used again.
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    public string IntoString()
    {
        var rval = String;
        Dispose();
        return rval;
    }

    /// Frees the native Rust memory. Safe to call multiple times.
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    public void Dispose()
    {
        if (_ptr == IntPtr.Zero) return;
        var _unmanaged = new Unmanaged();
        _unmanaged._ptr = _ptr;
        _unmanaged._len = _len;
        _unmanaged._capacity = _capacity;
        InteropHelper.interoptopus_string_destroy(_unmanaged);
        _ptr = IntPtr.Zero;
    }

    /// Creates an independent copy of this string, backed by a new Rust allocation.
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    public Utf8String Clone()
    {
        var _new = new Unmanaged();
        var _this = AsUnmanaged();
        InteropHelper.interoptopus_string_clone(ref _this, ref _new);
        return _new.IntoManaged();
    }

    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    [Obsolete("This method is intended for use by generated code only.")]
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal Unmanaged IntoUnmanaged()
    {
        if (_ptr == IntPtr.Zero) { throw new Exception(); }
        var _unmanaged = new Unmanaged();
        _unmanaged._ptr = _ptr;
        _unmanaged._len = _len;
        _unmanaged._capacity = _capacity;
        _ptr = IntPtr.Zero;
        return _unmanaged;
    }

    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    [Obsolete("This method is intended for use by generated code only.")]
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal Unmanaged AsUnmanaged()
    {
        var _unmanaged = new Unmanaged();
        _unmanaged._ptr = _ptr;
        _unmanaged._len = _len;
        _unmanaged._capacity = _capacity;
        return _unmanaged;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe struct Unmanaged
    {
        public IntPtr _ptr;
        public ulong _len;
        public ulong _capacity;

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        [Obsolete("This method is intended for use by generated code only.")]
        [EditorBrowsable(EditorBrowsableState.Never)]
        internal Utf8String IntoManaged()
        {
            var _managed = new Utf8String();
            _managed._ptr = _ptr;
            _managed._len = _len;
            _managed._capacity = _capacity;
            return _managed;
        }

    }

    internal partial class InteropHelper
    {
        [LibraryImport(Interop.NativeLib, EntryPoint = "interoptopus_string_create")]
        [MethodImpl(MethodImplOptions.AggressiveOptimization)]

        public static partial long interoptopus_string_create(IntPtr utf8, ulong len, out Unmanaged rval);

        [LibraryImport(Interop.NativeLib, EntryPoint = "interoptopus_string_destroy")]
        [MethodImpl(MethodImplOptions.AggressiveOptimization)]

        public static partial long interoptopus_string_destroy(Unmanaged utf8);

        [LibraryImport(Interop.NativeLib, EntryPoint = "interoptopus_string_clone")]
        [MethodImpl(MethodImplOptions.AggressiveOptimization)]

        public static partial long interoptopus_string_clone(ref Unmanaged orig, ref Unmanaged cloned);
    }

    [CustomMarshaller(typeof(Utf8String), MarshalMode.Default, typeof(Marshaller))]
    private struct MarshallerMeta { }

    internal ref struct Marshaller
    {
        private Utf8String _managed; // Used when converting managed -> unmanaged
        private Unmanaged _unmanaged; // Used when converting unmanaged -> managed

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public Marshaller(Utf8String managed) { _managed = managed; }
        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public Marshaller(Unmanaged unmanaged) { _unmanaged = unmanaged; }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public void FromManaged(Utf8String managed) { _managed = managed; }
        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public void FromUnmanaged(Unmanaged unmanaged) { _unmanaged = unmanaged; }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public unsafe Unmanaged ToUnmanaged()
        {
            return _managed.IntoUnmanaged();
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public unsafe Utf8String ToManaged()
        {
            return _unmanaged.IntoManaged();
        }

        [MethodImpl(MethodImplOptions.AggressiveOptimization)]
        public void Free() { }
    }
}


/// Convenience extension to convert a <see cref="string"/> to a <see cref="Utf8String"/>.
public static class StringExtensions
{
    /// Converts this string to a Rust-owned <see cref="Utf8String"/>.
    /// Call <see cref="Utf8String.Dispose"/> if the value is not passed back to Rust.
    public static Utf8String Utf8(this string s) { return Utf8String.From(s); }
}

public class InteropException(string text) : Exception(text) { }

public class EnumException() : InteropException($"Enum variant mismatch.")  { }

public class EnumException<T>(T t) : InteropException($"Enum variant mismatch.")
{
    public T Value { get; } = t;
}

[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
internal delegate void AsyncCallbackCommon(IntPtr data, IntPtr callback_data);

/// Wire-level discriminant for <c>AsyncOutcome&lt;T&gt;</c> on the Rust side
/// (see <c>interoptopus::pattern::asynk::AsyncOutcome</c>). Layout is
/// <c>#[repr(C, u8)]</c>: a one-byte tag at offset 0, then natural padding,
/// then the payload (only valid for <c>Ok</c>).
internal static class AsyncOutcomeTag
{
    public const byte Ok = 0;
    public const byte Cancelled = 1;
}

/// Mirror of Rust's <c>AsyncOutcome&lt;T&gt;</c>. Used both to read incoming
/// callback payloads and to construct outgoing ones from .NET plugins.
[StructLayout(LayoutKind.Sequential)]
internal struct AsyncOutcomeOf<T> where T : unmanaged
{
    public byte Tag;
    public T Value;
}

[StructLayout(LayoutKind.Sequential)]
internal partial struct AsyncCallbackCommonNative
{
    internal IntPtr _ptr;
    internal IntPtr _ts;
}

internal partial struct AsyncCallbackCommonNative
{
    /// Signals normal completion with no return value (corresponds to
    /// <c>AsyncCallback&lt;()&gt;</c> on the Rust side). Sends an
    /// <c>AsyncOutcome::Ok(())</c> tag (single zero byte).
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    [Obsolete("This method is intended for use by generated code only.")]
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal unsafe void UnsafeComplete()
    {
        if (_ptr == IntPtr.Zero) return;
        var fn = (delegate* unmanaged[Cdecl]<void*, IntPtr, void>)_ptr;
        byte tag = AsyncOutcomeTag.Ok;
        fn(&tag, _ts);
    }

    /// Signals normal completion with a value (corresponds to
    /// <c>AsyncCallback&lt;T&gt;</c> on the Rust side). Wraps <paramref name="t"/>
    /// in <c>AsyncOutcome::Ok</c> on the wire.
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    [Obsolete("This method is intended for use by generated code only.")]
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal unsafe void UnsafeComplete<T>(T t) where T : unmanaged
    {
        if (_ptr == IntPtr.Zero) return;
        var fn = (delegate* unmanaged[Cdecl]<AsyncOutcomeOf<T>*, IntPtr, void>)_ptr;
        var outcome = new AsyncOutcomeOf<T> { Tag = AsyncOutcomeTag.Ok, Value = t };
        fn(&outcome, _ts);
    }

    /// Signals cancellation. The Rust side will resolve the future to
    /// <c>Err(AsyncCancelled)</c>. Sends an <c>AsyncOutcome::Cancelled</c>
    /// tag (single byte equal to <c>1</c>); no payload follows.
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    [Obsolete("This method is intended for use by generated code only.")]
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal unsafe void UnsafeCompleteCancelled()
    {
        if (_ptr == IntPtr.Zero) return;
        var fn = (delegate* unmanaged[Cdecl]<void*, IntPtr, void>)_ptr;
        byte tag = AsyncOutcomeTag.Cancelled;
        fn(&tag, _ts);
    }
}

[CustomMarshaller(typeof(string), MarshalMode.ManagedToUnmanagedOut, typeof(ConstCStrMarshaller))]
internal static class ConstCStrMarshaller
{
    public static unsafe string? ConvertToManaged(byte* unmanaged)
        => unmanaged == null ? null : Marshal.PtrToStringAnsi((nint)unmanaged);
}

[StructLayout(LayoutKind.Sequential)]
internal partial struct TaskHandle
{
    private IntPtr _data;
    private IntPtr _abort_fn;
    private IntPtr _drop_fn;
}

internal partial struct TaskHandle : IDisposable
{
    /// Aborts the associated Rust async task. The spawned future will be
    /// dropped at its next <c>.await</c> point and the completion callback
    /// will fire with a <c>Panic</c> result.
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    [Obsolete("This method is intended for use by generated code only.")]
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal unsafe void Abort()
    {
        if (_abort_fn != IntPtr.Zero && _data != IntPtr.Zero)
        {
            ((delegate* unmanaged[Cdecl]<IntPtr, void>)_abort_fn)(_data);
        }
    }

    /// Frees the native handle resources without aborting the task.
    /// Must be called exactly once when the handle is no longer needed.
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    [Obsolete("This method is intended for use by generated code only.")]
    [EditorBrowsable(EditorBrowsableState.Never)]
    public unsafe void Dispose()
    {
        if (_drop_fn != IntPtr.Zero && _data != IntPtr.Zero)
        {
            ((delegate* unmanaged[Cdecl]<IntPtr, void>)_drop_fn)(_data);
            _data = IntPtr.Zero;
            _abort_fn = IntPtr.Zero;
            _drop_fn = IntPtr.Zero;
        }
    }

    /// Creates a <see cref="TaskHandle"/> backed by a <see cref="CancellationTokenSource"/>.
    /// Calling <c>Abort</c> on the returned handle triggers <see cref="CancellationTokenSource.Cancel()"/>;
    /// calling <c>Dispose</c> frees the pinned GCHandle.
    [MethodImpl(MethodImplOptions.AggressiveOptimization)]
    [Obsolete("This method is intended for use by generated code only.")]
    [EditorBrowsable(EditorBrowsableState.Never)]
    internal static unsafe TaskHandle FromCancellationTokenSource(CancellationTokenSource cts)
    {
        var gcHandle = GCHandle.Alloc(cts);
        return new TaskHandle
        {
            _data = GCHandle.ToIntPtr(gcHandle),
            _abort_fn = (IntPtr)(delegate* unmanaged[Cdecl]<IntPtr, void>)&TaskHandleAbort,
            _drop_fn = (IntPtr)(delegate* unmanaged[Cdecl]<IntPtr, void>)&TaskHandleDrop,
        };
    }

    [UnmanagedCallersOnly(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    private static void TaskHandleAbort(IntPtr data)
    {
        var handle = GCHandle.FromIntPtr(data);
        if (handle.Target is CancellationTokenSource cts)
        {
            cts.Cancel();
        }
    }

    [UnmanagedCallersOnly(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvCdecl) })]
    private static void TaskHandleDrop(IntPtr data)
    {
        var handle = GCHandle.FromIntPtr(data);
        if (handle.Target is CancellationTokenSource cts)
        {
            cts.Cancel();
            cts.Dispose();
        }
        handle.Free();
    }
}

/// <summary> A Unit type to represent Rust's <c>()</c>. </summary>
public struct Unit : IEquatable<Unit>
{
    /// <summary> The default unit value. </summary>
    public static readonly Unit Default;

    /// <inheritdoc/>
    public bool Equals(Unit other) => true;

    /// <inheritdoc/>
    public override bool Equals(object? obj) => obj is Unit;
    /// <inheritdoc/>
    public override int GetHashCode() => 0;

    /// <inheritdoc/>
    public override string ToString() => "()";
}

/// <summary> A result type to represent Rust's <c>Result&lt;T, E&gt;</c>. </summary>
/// <typeparam name="T"> The <c>Ok</c> type. </typeparam>
/// <typeparam name="TErr"> The <c>Err</c> type. </typeparam>
public interface IResult<out T, out TErr>
{
    /// <summary> Returns <c>true</c> if the result is <c>Ok</c>; otherwise, <c>false</c>. </summary>
    bool IsOk { get; }
    /// <summary> Returns <c>true</c> if the result is <c>Err</c>; otherwise, <c>false</c>. </summary>
    bool IsErr { get; }
    /// <summary> Returns <c>true</c> if the Rust implementation has panicked; otherwise, <c>false</c>. </summary>
    bool IsPanic { get; }
    /// <summary> Returns <c>true</c> if an invalid null was passed; otherwise, <c>false</c>. </summary>
    bool IsNull { get; }

    /// <summary> Unwraps the value of the result. </summary>
    /// <returns> The value, if the result is <see cref="IsOk"/>. </returns>
    /// <exception cref="EnumException{T}"> Thrown if the result is not <c>Ok</c>. </exception>
    T AsOk();
    /// <summary> Unwraps the error of the result. </summary>
    /// <returns> The error, if the result is <see cref="IsErr"/>. </returns>
    /// <exception cref="EnumException{TErr}"> Thrown if the result is not <c>Err</c>. </exception>
    TErr AsErr();

    /// <summary> Returns the exception for the internal result variant. </summary>
    /// <returns> An <see cref="EnumException{T}"/> or <see cref="EnumException{TErr}"/> for <c>Ok</c> / <c>Err</c> state, or an <see cref="EnumException"/> otherwise. </returns>
    Exception ExceptionForVariant();
}
